name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v12

    - name: Configure CMake
      run: nix develop --command cmake -B build -G Ninja

    - name: Build Project
      run: nix develop --command cmake --build build

    - name: Run Unit Tests
      run: nix develop --command ./build/fixure_tests
